# Generated by Django 3.2.18 on 2023-04-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='encrypted_data',
            field=models.CharField(default='empty', max_length=500),
        ),
    ]
