# Generated by Django 3.2.18 on 2023-04-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0002_userrequest_encrypted_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='encrypted_data',
            field=models.CharField(default='empty', max_length=10000),
        ),
    ]
