# Generated by Django 3.2.18 on 2023-04-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0003_alter_userrequest_encrypted_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='fileid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
